/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as UnidadeRouteImport } from './routes/unidade'
import { Route as PrazoRevisaoRouteImport } from './routes/prazo-revisao'
import { Route as NotificacoesRouteImport } from './routes/notificacoes'
import { Route as GerenciamentoAnalistasRouteImport } from './routes/gerenciamento-analistas'
import { Route as AnalistasRouteImport } from './routes/analistas'
import { Route as AnalistaIdRouteImport } from './routes/$analistaId'
import { Route as IndexRouteImport } from './routes/index'
import { Route as RevisaoProcessIdRouteImport } from './routes/revisao.$processId'
import { Route as HistoricoProcessIdRouteImport } from './routes/historico.$processId'

const UnidadeRoute = UnidadeRouteImport.update({
  id: '/unidade',
  path: '/unidade',
  getParentRoute: () => rootRouteImport,
} as any)
const PrazoRevisaoRoute = PrazoRevisaoRouteImport.update({
  id: '/prazo-revisao',
  path: '/prazo-revisao',
  getParentRoute: () => rootRouteImport,
} as any)
const NotificacoesRoute = NotificacoesRouteImport.update({
  id: '/notificacoes',
  path: '/notificacoes',
  getParentRoute: () => rootRouteImport,
} as any)
const GerenciamentoAnalistasRoute = GerenciamentoAnalistasRouteImport.update({
  id: '/gerenciamento-analistas',
  path: '/gerenciamento-analistas',
  getParentRoute: () => rootRouteImport,
} as any)
const AnalistasRoute = AnalistasRouteImport.update({
  id: '/analistas',
  path: '/analistas',
  getParentRoute: () => rootRouteImport,
} as any)
const AnalistaIdRoute = AnalistaIdRouteImport.update({
  id: '/$analistaId',
  path: '/$analistaId',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const RevisaoProcessIdRoute = RevisaoProcessIdRouteImport.update({
  id: '/revisao/$processId',
  path: '/revisao/$processId',
  getParentRoute: () => rootRouteImport,
} as any)
const HistoricoProcessIdRoute = HistoricoProcessIdRouteImport.update({
  id: '/historico/$processId',
  path: '/historico/$processId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/$analistaId': typeof AnalistaIdRoute
  '/analistas': typeof AnalistasRoute
  '/gerenciamento-analistas': typeof GerenciamentoAnalistasRoute
  '/notificacoes': typeof NotificacoesRoute
  '/prazo-revisao': typeof PrazoRevisaoRoute
  '/unidade': typeof UnidadeRoute
  '/historico/$processId': typeof HistoricoProcessIdRoute
  '/revisao/$processId': typeof RevisaoProcessIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/$analistaId': typeof AnalistaIdRoute
  '/analistas': typeof AnalistasRoute
  '/gerenciamento-analistas': typeof GerenciamentoAnalistasRoute
  '/notificacoes': typeof NotificacoesRoute
  '/prazo-revisao': typeof PrazoRevisaoRoute
  '/unidade': typeof UnidadeRoute
  '/historico/$processId': typeof HistoricoProcessIdRoute
  '/revisao/$processId': typeof RevisaoProcessIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/$analistaId': typeof AnalistaIdRoute
  '/analistas': typeof AnalistasRoute
  '/gerenciamento-analistas': typeof GerenciamentoAnalistasRoute
  '/notificacoes': typeof NotificacoesRoute
  '/prazo-revisao': typeof PrazoRevisaoRoute
  '/unidade': typeof UnidadeRoute
  '/historico/$processId': typeof HistoricoProcessIdRoute
  '/revisao/$processId': typeof RevisaoProcessIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/$analistaId'
    | '/analistas'
    | '/gerenciamento-analistas'
    | '/notificacoes'
    | '/prazo-revisao'
    | '/unidade'
    | '/historico/$processId'
    | '/revisao/$processId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/$analistaId'
    | '/analistas'
    | '/gerenciamento-analistas'
    | '/notificacoes'
    | '/prazo-revisao'
    | '/unidade'
    | '/historico/$processId'
    | '/revisao/$processId'
  id:
    | '__root__'
    | '/'
    | '/$analistaId'
    | '/analistas'
    | '/gerenciamento-analistas'
    | '/notificacoes'
    | '/prazo-revisao'
    | '/unidade'
    | '/historico/$processId'
    | '/revisao/$processId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AnalistaIdRoute: typeof AnalistaIdRoute
  AnalistasRoute: typeof AnalistasRoute
  GerenciamentoAnalistasRoute: typeof GerenciamentoAnalistasRoute
  NotificacoesRoute: typeof NotificacoesRoute
  PrazoRevisaoRoute: typeof PrazoRevisaoRoute
  UnidadeRoute: typeof UnidadeRoute
  HistoricoProcessIdRoute: typeof HistoricoProcessIdRoute
  RevisaoProcessIdRoute: typeof RevisaoProcessIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/unidade': {
      id: '/unidade'
      path: '/unidade'
      fullPath: '/unidade'
      preLoaderRoute: typeof UnidadeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/prazo-revisao': {
      id: '/prazo-revisao'
      path: '/prazo-revisao'
      fullPath: '/prazo-revisao'
      preLoaderRoute: typeof PrazoRevisaoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/notificacoes': {
      id: '/notificacoes'
      path: '/notificacoes'
      fullPath: '/notificacoes'
      preLoaderRoute: typeof NotificacoesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gerenciamento-analistas': {
      id: '/gerenciamento-analistas'
      path: '/gerenciamento-analistas'
      fullPath: '/gerenciamento-analistas'
      preLoaderRoute: typeof GerenciamentoAnalistasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/analistas': {
      id: '/analistas'
      path: '/analistas'
      fullPath: '/analistas'
      preLoaderRoute: typeof AnalistasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$analistaId': {
      id: '/$analistaId'
      path: '/$analistaId'
      fullPath: '/$analistaId'
      preLoaderRoute: typeof AnalistaIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/revisao/$processId': {
      id: '/revisao/$processId'
      path: '/revisao/$processId'
      fullPath: '/revisao/$processId'
      preLoaderRoute: typeof RevisaoProcessIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/historico/$processId': {
      id: '/historico/$processId'
      path: '/historico/$processId'
      fullPath: '/historico/$processId'
      preLoaderRoute: typeof HistoricoProcessIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AnalistaIdRoute: AnalistaIdRoute,
  AnalistasRoute: AnalistasRoute,
  GerenciamentoAnalistasRoute: GerenciamentoAnalistasRoute,
  NotificacoesRoute: NotificacoesRoute,
  PrazoRevisaoRoute: PrazoRevisaoRoute,
  UnidadeRoute: UnidadeRoute,
  HistoricoProcessIdRoute: HistoricoProcessIdRoute,
  RevisaoProcessIdRoute: RevisaoProcessIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
