/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as UnidadeRouteImport } from './routes/unidade'
import { Route as NotificacoesRouteImport } from './routes/notificacoes'
import { Route as IndexRouteImport } from './routes/index'
import { Route as RevisaoProcessIdRouteImport } from './routes/revisao.$processId'
import { Route as HistoricoProcessIdRouteImport } from './routes/historico.$processId'

const UnidadeRoute = UnidadeRouteImport.update({
  id: '/unidade',
  path: '/unidade',
  getParentRoute: () => rootRouteImport,
} as any)
const NotificacoesRoute = NotificacoesRouteImport.update({
  id: '/notificacoes',
  path: '/notificacoes',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const RevisaoProcessIdRoute = RevisaoProcessIdRouteImport.update({
  id: '/revisao/$processId',
  path: '/revisao/$processId',
  getParentRoute: () => rootRouteImport,
} as any)
const HistoricoProcessIdRoute = HistoricoProcessIdRouteImport.update({
  id: '/historico/$processId',
  path: '/historico/$processId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/notificacoes': typeof NotificacoesRoute
  '/unidade': typeof UnidadeRoute
  '/historico/$processId': typeof HistoricoProcessIdRoute
  '/revisao/$processId': typeof RevisaoProcessIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/notificacoes': typeof NotificacoesRoute
  '/unidade': typeof UnidadeRoute
  '/historico/$processId': typeof HistoricoProcessIdRoute
  '/revisao/$processId': typeof RevisaoProcessIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/notificacoes': typeof NotificacoesRoute
  '/unidade': typeof UnidadeRoute
  '/historico/$processId': typeof HistoricoProcessIdRoute
  '/revisao/$processId': typeof RevisaoProcessIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/notificacoes'
    | '/unidade'
    | '/historico/$processId'
    | '/revisao/$processId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/notificacoes'
    | '/unidade'
    | '/historico/$processId'
    | '/revisao/$processId'
  id:
    | '__root__'
    | '/'
    | '/notificacoes'
    | '/unidade'
    | '/historico/$processId'
    | '/revisao/$processId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  NotificacoesRoute: typeof NotificacoesRoute
  UnidadeRoute: typeof UnidadeRoute
  HistoricoProcessIdRoute: typeof HistoricoProcessIdRoute
  RevisaoProcessIdRoute: typeof RevisaoProcessIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/unidade': {
      id: '/unidade'
      path: '/unidade'
      fullPath: '/unidade'
      preLoaderRoute: typeof UnidadeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/notificacoes': {
      id: '/notificacoes'
      path: '/notificacoes'
      fullPath: '/notificacoes'
      preLoaderRoute: typeof NotificacoesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/revisao/$processId': {
      id: '/revisao/$processId'
      path: '/revisao/$processId'
      fullPath: '/revisao/$processId'
      preLoaderRoute: typeof RevisaoProcessIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/historico/$processId': {
      id: '/historico/$processId'
      path: '/historico/$processId'
      fullPath: '/historico/$processId'
      preLoaderRoute: typeof HistoricoProcessIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  NotificacoesRoute: NotificacoesRoute,
  UnidadeRoute: UnidadeRoute,
  HistoricoProcessIdRoute: HistoricoProcessIdRoute,
  RevisaoProcessIdRoute: RevisaoProcessIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
