/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as RevisaoProcessIdRouteImport } from './routes/revisao.$processId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const RevisaoProcessIdRoute = RevisaoProcessIdRouteImport.update({
  id: '/revisao/$processId',
  path: '/revisao/$processId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/revisao/$processId': typeof RevisaoProcessIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/revisao/$processId': typeof RevisaoProcessIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/revisao/$processId': typeof RevisaoProcessIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/revisao/$processId'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/revisao/$processId'
  id: '__root__' | '/' | '/revisao/$processId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  RevisaoProcessIdRoute: typeof RevisaoProcessIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/revisao/$processId': {
      id: '/revisao/$processId'
      path: '/revisao/$processId'
      fullPath: '/revisao/$processId'
      preLoaderRoute: typeof RevisaoProcessIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  RevisaoProcessIdRoute: RevisaoProcessIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
